=== TomasHofman/dom4j/dom4j/xml/schema/test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns='http://www.w3.org/2001/XMLSchema'>

 <element name="records">
  <complexType>
   <sequence>
     <element ref="record" minOccurs='1' maxOccurs='unbounded'/>
   </sequence>
  </complexType>
 </element>

 <element name="record">
  <complexType>
    <attribute name="durationTag" type="duration"/>
    <attribute name="dateTag" type="date"/>
    <attribute name="timeTag" type="time"/>
    <attribute name="dateTimeTag" type="dateTime"/>
    <attribute name="gYearMonthTag" type="gYearMonth"/>
    <attribute name="gYearTag" type="gYear"/>
    <attribute name="gMonthDayTag" type="gMonthDay"/>
    <attribute name="gDayTag" type="gDay"/>
    <attribute name="gMonthTag" type="gMonth"/>

    <attribute name="booleanTag" type="boolean"/>
    <attribute name="base64BinaryTag" type="base64Binary"/>
    <attribute name="hexBinaryTag" type="hexBinary"/>


    <attribute name="floatTag" type="float"/>
    <attribute name="doubleTag" type="double"/>

    <attribute name="decimalTag" type="decimal"/>
    <attribute name="integerTag" type="integer"/>

    <attribute name="nonPositiveIntegerTag" type="nonPositiveInteger"/>
    <attribute name="negativeIntegerTag" type="negativeInteger"/>

    <attribute name="longTag" type="long"/>
    <attribute name="intTag" type="int"/>
    <attribute name="shortTag" type="short"/>
    <attribute name="byteTag" type="byte"/>

    <attribute name="nonNegativeIntegerTag" type="nonNegativeInteger"/>
    <attribute name="unsignedLongTag" type="unsignedLong"/>
    <attribute name="unsignedIntTag" type="unsignedInt"/>
    <attribute name="unsignedShortTag" type="unsignedShort"/>
    <attribute name="unsignedByteTag" type="unsignedByte"/>

    <attribute name="positiveIntegerTag" type="positiveInteger"/>

  </complexType>
 </element>

</schema>

=== TomasHofman/dom4j/dom4j/xml/schema/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<records 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:noNamespaceSchemaLocation='test.xsd'>

  <record id="foo">
    <floatTag>123.45</floatTag>
    <doubleTag>123.45</doubleTag>

    <decimalTag>123</decimalTag>
    <integerTag>123</integerTag>

    <nonPositiveIntegerTag>-123</nonPositiveIntegerTag>
    <negativeIntegerTag>-123</negativeIntegerTag>

    <longTag>12345678901234</longTag>
    <intTag>12345</intTag>
    <shortTag>1234</shortTag>
    <byteTag>123</byteTag>

    <nonNegativeIntegerTag>123</nonNegativeIntegerTag>
    <unsignedLongTag>123</unsignedLongTag>
    <unsignedIntTag>123</unsignedIntTag>
    <unsignedShortTag>123</unsignedShortTag>
    <unsignedByteTag>123</unsignedByteTag>

    <positiveIntegerTag>123</positiveIntegerTag>

    <dateTag>1999-05-03</dateTag>
    <dateTimeTag>1999-05-31T13:20:00-05:00</dateTimeTag>
  </record>

</records>
